In [2]:
list=[1],[2],[3]
list

([1], [2], [3])

In [3]:
import pandas as pd
import numpy as np

In [6]:
list1=[1],[4],[6]
list1

([1], [4], [6])

In [7]:
list2=[1,4,6]
list2

[1, 4, 6]

In [8]:
type(list1)

tuple

In [9]:
type(list2)

list

In [10]:
list3=(1,2,3)

In [11]:
list3

(1, 2, 3)

In [12]:
type(list3)

tuple

In [13]:
list2.append(3)

In [14]:
list2

[1, 4, 6, 3]

In [15]:
arr=np.array([1,2,4,4,5])

In [16]:
arr

array([1, 2, 4, 4, 5])

In [17]:
type(arr)

numpy.ndarray

In [18]:
arr2=np.random.randint(2,6,7)


In [19]:
arr2


array([4, 5, 3, 5, 2, 2, 3])

In [20]:
np.arange(3,9,1)

array([3, 4, 5, 6, 7, 8])

In [21]:
np.array([[2,3],[5,7]])

array([[2, 3],
       [5, 7]])

In [22]:
randarray=np.random.randint(1, 5, size=(3,3))

In [23]:
randarray

array([[4, 2, 1],
       [1, 2, 2],
       [3, 1, 1]])

In [24]:
randarray[0:3]

array([[4, 2, 1],
       [1, 2, 2],
       [3, 1, 1]])

In [25]:
a=np.array([[ 0, 4, 2],[ 9, 3, 7]])

In [26]:
np.linalg.matrix_rank(a)

2

In [27]:
a = np.array([11, 12, 13, 14])
b = np.array([1, 2, 3, 4])
c = a - b

In [28]:
c

array([10, 10, 10, 10])

In [29]:
a = 9/2
b = 5.2/2

In [30]:
a

4.5

In [31]:
b

2.6

In [35]:
a=np.array([5,8,12,65])

In [36]:
a

array([ 5,  8, 12, 65])

In [37]:
A=np.array([1, 2, 3])

In [39]:
a1 = [1, 3] 
b1 = a1
a1[0] = 4 
print(b1)

[4, 3]


In [40]:
min(max(False,-3,-4), 2,7)

False

In [41]:
len(["hi",6, 9, 5])

4